kim: kim_heer_2018.zip
	unzip kim_heer_2018.zip 'visual-encoding-effectiveness-data-7deb0ddad14b33bff7a00fe8188acb54fd7b30a6/stimuli/data/*' -d .
	mkdir kim
	mv visual-encoding-effectiveness-data-7deb0ddad14b33bff7a00fe8188acb54fd7b30a6/stimuli/data/datasets/* kim/
	rm -r visual-encoding-effectiveness-data-7deb0ddad14b33bff7a00fe8188acb54fd7b30a6

kim_heer_2018.zip:
	wget https://github.com/uwdata/visual-encoding-effectiveness-data/archive/7deb0ddad14b33bff7a00fe8188acb54fd7b30a6.zip -O kim_heer_2018.zip
